language: cpp
before_script:
  sudo apt-get install libboost-test-dev -y
  sudo apt-get install libgtest-dev -y
script:
- cmake .
- cmake --build .
- ctest .
- cmake --build . --target package
deploy:
  provider: bintray
  file: description.json
  user: $BINTRAY_USER
  key: $BINTRAY_API_KEY
  skip_cleanup: true