language: cpp
script:
- cmake .
- cmake --build .
- cmake --build . --target test_version
- cmake --build . --target package
deploy:
  provider: bintray
  file: FILE
  user: ceber9huh
  key: $BINTRAY_API_KEY
  skip_cleanup: true